import { ThemeProvider } from "@wrksz/themes/next"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import "./globals.css"
import { Providers } from "@/app/providers"
import { ReduxProvider } from "@/components/redux-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <ThemeProvider
            defaultTheme="dark"
            themes={["light", "dark"]}
            attribute="class"
            storage="cookie"
          >
            <Providers>{children}</Providers>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  )
}
